# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  containers:
    - container: my_container
      image: jeffersonhealth/node-oracle-instantclient

pool:
  vmImage: "ubuntu-16.04"

container: my_container

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "9.x"
    displayName: "Install Node.js"

  - script: |
      npm install
      npm run compile
    displayName: "npm install and compile"

  - script: npm run utest
